### ISSUE TITLE
[3D view] Spinning behaviour.

### ISSUE THREAD

**Issue by Genert** [TTimo/GtkRadiant#111]
I am having some weird issue where I try to use the 3D view in GtkRadiant but when I do it spins around uncontrollably and extremely fast. I've changed the mouse speed, restarting my computer, uninstalling it, disabling composition and I have searched on Google with no results. A few days ago I was having no problem at all with this, now it just suddenly appears. I'm using GtkRadiant 1.6 and I use Windows 7.

Originally posted by Bathory @ http://forums.warchestgames.com/showthread.php/32584-Weird-GtkRadiant-issue?p=404102

**Comment by TTimo** [comment]
Should be fixed in latest build - see website
