### ISSUE TITLE
[REQUEST] Arrows on info_ut_spawn

### ISSUE THREAD

**Issue by Majki** [TTimo/GtkRadiant#131]
info_player_start has arrow indicating "angle" value. Can we get similar one for info_ut_spawn?
PIC:
http://i.imagebanana.com/img/qljbsf5m/Zaznaczenie_041.png

**Comment by TTimo** [comment]
It doesn't have to be in code, but I'm concerned that the documentation for info_ut_spawn doesn't mention the 'angle' key?

Added the 'angle' flag in urbanterror.def (at svn rev 136) - this should fix it. Could be a good idea to get an updated def file from FS too.
