### ISSUE TITLE
Right-click mouse control with windows 2 button/quad layout

### ISSUE THREAD

**Issue by shadowspawn** [TTimo/GtkRadiant#149]
When using a dry install of 1.6 off of icculus's site, gtkradiant 1.6.20121007, and I use the mouse to right-click and drag any XYZ window (in XYZ/Cam quad layout, 2 button mouse controls) the mouse seems to go a little wonky.

1.4, 1.5 doesn't do this. It's only in the XYZ, camera operates fine.

It's not any particular mouse driver, tried it/reproduced on a completely dry install of windows 7 (I had a spare computer laying around to duplicate). It just seems when I right-click and drag, the selected screen speeds out of control. 

Also, right before sending, I tested on an older dual P3 Xeon/Quadro Dell (just an old cad station) and it _also_ does it.

**Comment by TTimo** [comment]
Should be fixed in latest build - see website
