### ISSUE TITLE
Cylinder + Surface Inspector crash

### ISSUE THREAD

**Issue by Pande** [TTimo/GtkRadiant#155]
Create a cylinder press "S" to enter the surface inspector window and click the "Axial" button: that causes GtkRadiant 1.6.3 to crash with no error message. Quits to desktop.

**Comment by Pan7** [comment]
When you create a brush, click axial in the surface inspector and create a cylinder then its crashing when you click axial again.

**Comment by Pan7** [comment]
Can anyone test if this problem is gone with the latest version of gtkradiant?

**Comment by 0bsidian** [comment]
Works okay. No longer crashes.
