### ISSUE TITLE
Camera wildly rotates in freelook mode

### ISSUE THREAD

**Issue by flackbaume** [TTimo/GtkRadiant#237]
When loading an arbitrary map (tested Quake 3 Arena and RTCW maps) and right-clicking in the camera-window, the camera starts to rotate clockwise around the up-axis. I have Windows 7 64bit, Intel i7 and two GTX460. I tried
- restart (of course)
- disableing SLI
- switching the mouse
- running as admin and in compatability mode (WinXP SP3)
- fiddling around with the preferences

and well.... I wouldn't be writing this if anything solved the problem ;)

Best regards

**Comment by TTimo** [comment]
Should be fixed in latest build - see website
