### ISSUE TITLE
GtkRadiant-1.6.4 compile issue

### ISSUE THREAD

**Issue by gilazuzu** [TTimo/GtkRadiant#246]
QL compiler will not compile light -

Bat compile will compile light, but there are shader issue, cloud act like a wall and jumppad shader get compressed.

my bat compile
"C:\mypath\q3map2.exe" -meta -threads 1 "C:\mypath\baseq3\maps\room.map"
"C:\mypath\q3map2.exe" -vis -saveprt -threads 1 "C:\mypath\baseq3\maps\room.bsp"
"C:\mypath\q3map2.exe" -light -fast -super 2 -filter -patchshadows -threads 1 "C:\mypath\baseq3\maps\room.bsp"
pause

video download off the issue
http://www.gilazuzu.dk/3d/bug_report.zip

**Comment by Pan7** [comment]
This issue is old. Please try the latest build and repost the problem if it still exists.
