### ISSUE TITLE
"fixed size" from Radiant 1.5

### ISSUE THREAD

**Issue by Majki** [TTimo/GtkRadiant#252]
Could we get "fixed size" for texture browser from Radiant 1.5? Functionality described here:

https://dl.dropboxusercontent.com/u/5856916/pics/fixedcsnonfixed.png

It makes all textures uniformed scaled in texture browser. Very helpful when we have 512+ and 64- sized textures mixed up in texture browser window.

**Comment by Pan7** [comment]
Starting with GtkRadiant-1.6.5-20180806 there should be a fixed size texture feature.
