### ISSUE TITLE
GTKradiant 1.6.4 doesn't work with windows 7

### ISSUE THREAD

**Issue by Aliebak** [TTimo/GtkRadiant#258]
gtk radiant 1.6 
can't compile bsp
Failed to execute the following command "D:/gtkradiant 1.6/gtkRadiant-1.6.4-20131213/x64/q3map2" -v -connect 127.0.0.1:39000 -game quake3 -fs_basepath "/Quake3/Baseq3/" -meta "/Quake3/baseq3/maps/test1.map"
Check that the file exists and that you don't run out of system recources

**Comment by thunderpwn** [comment]
It works fine with ET atleast I am running it at 64 bit windows 7 profesional

**Comment by Pan7** [comment]
This issue is old. Please try the latest build and repost the problem if it still exists.
