### ISSUE TITLE
The problem with bspc.exe when creating aas files RtCW

### ISSUE THREAD

**Issue by ShsYoshik** [TTimo/GtkRadiant#264]
Hi. For the create .aas navigation file to new map RtCW, I encountered such a problem: bspc.exe not understand command "-ext" and "%extraparms%". These commands are needed for creating two files "mapname_b0.aas" and  "mapname_b1.aas". Another issue   bspc.exe not understand in "aascfg_lg.c" and  "aascfg_sm.c" line rs_allowladders.

Use bspc.exe version from GtkRadiant 1.6.4

Error from logfile:
- unknown parameter -ext
- unknown parameter %extraparms%
- error: file aascfg_sm.c, line 65: unknown structure field rs_allowladders

Compile .bat-file:
@echo off
setlocal

rem Enable this next line to compile maps without debug info (put in a rem to enable debug info)
rem set extraparms=-optimize

bspc -threads 1 -ext _b0 -cfg aascfg_sm.c -bsp2aas ..\main\maps\depot.bsp -output ..\main\maps %extraparms%
copy bspc.log temp_b0.log
bspc -threads 1 -ext _b1 -cfg aascfg_lg.c -bsp2aas ..\main\maps\depot.bsp -output ..\main\maps %extraparms%
copy bspc.log temp_b1.log

p.s. excuse my bad english

**Comment by zturtleman** [comment]
The version of bspc included in GtkRadiant 1.6.4 is for Quake 3 and QuakeLive. It does not support RTCW's AAS format or it's additional arguments and cfg settings.

**Comment by TTimo** [comment]
As this is specific to RTCW it should be looked at by the developer in charge of RTCW support - @merlin1991 are you still around?

**Comment by merlin1991** [comment]
@TTimo  still around, given issues like #282 this might take a while

**Comment by TTimo** [comment]
Yeah we should wait for #282 to be addressed first.

**Comment by TTimo** [comment]
#282 has been addressed, more bspc fixes went into the latest 1.6.5 update
please report on the status of this - I will be closing this soon if there is no feedback

**Comment by zturtleman** [comment]
RTCW has it's own BSPC fork that creates AAS files that are not compatible with Quake 3. [TTimo/bspc](https://github.com/TTimo/bspc) does not support RTCW.

**Comment by TTimo** [comment]
@merlin1991 where can we pull working RTCW bspc source from?

**Comment by TTimo** [comment]
Closing / not a milestone 1.6.5 issue. Is a more general problem with RTCW support.
