### ISSUE TITLE
Linux 64bit bspc fails to create valid .aas

### ISSUE THREAD

**Issue by Tigger-oN** [TTimo/GtkRadiant#265]
The 64bit version of bspc fails to create a valid .aas file. The command appears to work but there are no error messages until launching the game.

Current solution / work around: Use the 32 bit version of bspc (requires the ability to run 32 bit programs on 64bit systems)

**Comment by TTimo** [comment]
There were some pull requests against the BSPC source for things that would clearly have broken Linux 64 bit. See https://github.com/TTimo/bspc/commits/master from today.

**Comment by TTimo** [comment]
More fixes went into latest 1.6.5 update, but probably still not 64 bit friendly.

**Comment by viciious** [comment]
I've tested win32 and win64 versions of bspc and both produce identical .aas files for my test map. Now lin64 is another story: the produced .aas file is notably bigger in size, yet it seems to be valid. From what I can tell, gcc generates x64 fp assembly which produces wildly different results when compared to x87.

**Comment by TTimo** [comment]
@Tigger-oN would you mind testing the latest BSPC with @viciious 's latest fixes and report back?
I'd like to release some binaries for GtkRadiant Linux with this 1.6.5 milestone.

**Comment by Tigger-oN** [comment]
Happy to test but not sure how to compile the source. Using command line / terminal. I'm familiar with running `make` but I'm not sure with this structure - seems like python? (which I don't use at all).

**Comment by Tigger-oN** [comment]
My older 32bit BSPC (Dec, 2013) makes an .aas of 1.67MB and the current 64bit BSPC .aas size (on the same .bsp) is 1.80MB. Bots do work however - yay!

**Comment by TTimo** [comment]
Yes the AAS file produced should work with any 32/64 bit engine just the same as if it was produced by a 32 bit bspc binary. As @viciious pointed out the float point code may behave differently between 32 and 64 bit, so it doesn't compute exactly the same file and the same AAS, but it's a valid AAS nevertheless.

Thanks for checking this out. I think we can close this.
