### ISSUE TITLE
.OBJ Texture Parsing

### ISSUE THREAD

**Issue by SzicoVII** [TTimo/GtkRadiant#269]
Would anyone be able to have a brief look into how Radiant currently tries to read .obj files? Ive been able to get both custom .ase,and .md3 conversions working, but not my converted to .obj files. The model loads fine in radiant, but there is no texture and I get a load of texture errors as below:

These are the errors flagged by radiant by loading the .obj (reminder, md3 conversion works fine)

vfsExtractRelativePath: success
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName
LOADED: textures/radiant/shadernotex
WARNING: Activate shader failed for maps/skin.tga
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName
FIXME: name == NULL || strlen(name) == 0 in QERApp_Shader_ForName

(And then a whole bunch more of these)

In the .obj file itself, using notepad++, the texture paths are as follows:

g rdmobj72
usemtl textures/platform/platform8 e.t.c.

But these do not appear to load in radiant.
# 

Additionally the map doesnt compile as it throws up about a million null shader errors and then gets a safe_malloc error -

 WARNING: Null or empty shader name
***********\* ERROR ************
safe_malloc failed on allocation of 1598880 bytes

(Rename this .jpg to .pk3 to get my test files)
![szico_objtest](https://cloud.githubusercontent.com/assets/4289750/3520734/65fae51a-0735-11e4-9dfd-f4af29927398.jpg)

**Comment by Pan7** [comment]
usemtl isn't supported yet.
