### ISSUE TITLE
GtkRadiant:Textures

### ISSUE THREAD

**Issue by yelworc98** [TTimo/GtkRadiant#270]
When i use GtkRadiant(newest version i could find)mac the textures are missing when i select them it only shows a missing texture pattern. I have tried to load a directory file from the game(Jedi Academy) but i do not know which too choose and i have tried many of the files in it. I have tried in Windows and Mac but they both have to same problem. Please show me how to fix this ?????  Also I can use windows and mac but please tell me how to fix in mac not windows and the game i am using is Jedi Academy.

**Comment by Pan7** [comment]
This issue is old. Please try the latest build and repost the problem if it still exists.
