### ISSUE TITLE
Feature Request: Coloured detail brushes in 2D views

### ISSUE THREAD

**Issue by 0bsidian** [TTimo/GtkRadiant#278]
Currently, it's a bit hard to distinguish between detail and structural brushes unless you keep hitting the filter keys. It would be useful to have detail brushes show up in the editor's 2D views as a different colour, much like how func_group objects show up blue, or how static meshes show up as orange.

**Comment by Mateos81** [comment]
After pulling and compiling (checked the merged content was in my fork), I don't have colored detail brushes (they're black when not in a func_group).

Is this not working only for me?
