### ISSUE TITLE
Doesn't Open on OS X Yosemite

### ISSUE THREAD

**Issue by circa-III** [TTimo/GtkRadiant#279]
Just downloaded GTKRadiant 1.6.4 for Mac, and it doesn't even open. 

I'm on OS X 10.10.1.

**Comment by RedRaspberry** [comment]
Im reopening this issue. I have tried to open XQuartz as a standalone and then open gtk to no avail. I have also opened gtk on its own, with the same result. All that happens is the app icon appears for a second, then disappears. It does not show as an open app in the dock, nor does it show in activity monitor. I have also installed all the dependencies from : sudo port install dylibbundler pkgconfig gtkglext scons .
