### ISSUE TITLE
Model Loading Behavior

### ISSUE THREAD

**Issue by freemancw** [TTimo/GtkRadiant#28]
Two issues:
- It would be nice if when the dialog popped up, there was an "all valid model formats" selected as the file filter, because it is annoying to have to manually swap between each one.
- Sometimes you'll start to load a model, and then decide you don't want to for some reason, cancel, and then you're left with an empty model handle. If you deselect it, it is a pain in the ass to get rid of because it's "infinitely small." In 1.5.0 this was okay because you could select a wide area. This threw me off when I first ran into it.

**Comment by Pan7** [comment]
Can anyone test this with the latest version of gtkradiant?

**Comment by 0bsidian** [comment]
Works great now. Thanks.
