### ISSUE TITLE
GTK failure due to synapse.config , global.xlink,local.pref 

### ISSUE THREAD

**Issue by KwaiChangCane** [TTimo/GtkRadiant#281]
http://pastie.org/private/6drnb67ahv6rvkxys14pa  this is what i get trying to run radiant for Nexuiz . i have pulled the nexuiz pack from the netradiant folder to see if that would work but it doesnt . so id there a nexuiz gamepack somewhere that works or can i fix the issues in the link above ? 

The reason i want GTKradiant to work with nexuiz is because of the facedrag feature (Ctrl+LMB drag),not found in Netradiant . This tool will dramatically speed up mapping and acheive aspired geometry in my mapping . I could use the vertices but that seems to take too long on the scale i am shooting for . 

Thanks in advance for taking a look at this issue

**Comment by TTimo** [comment]
Nexuiz isn't supported in GtkRadiant 1.6.

Please consult the mission statement on the main page for a general explanation how more games could be supported: http://icculus.org/gtkradiant/

And the current list of supported games: http://icculus.org/gtkradiant/developers.html#gamepacks
