### ISSUE TITLE
1.6.4 BSPC.exe fails to generate .aas files

### ISSUE THREAD

**Issue by 0bsidian** [TTimo/GtkRadiant#282]
It seems as if a number of uses have been having difficulty using BSPC.exe in the latest GtkRadiant build, outputting invalid .aas files. I first started seeing reports from users having problems during the MapCore Quake 3 15th Anniversary contest. More recently on Quake3World. As a workaround, people are using different versions of BSPC to output working .aas files.

UPDATE: I've tried compiling q3dm1sample and then using it to generate the .aas. It fails with a message:

> The connection timed out, assuming the BSP process failed. Make sure you are using a networked version of Q2Map? Otherwise you need to disable BSP Monitoring in prefs

Discussion on this issue:
http://www.quake3world.com/forum/viewtopic.php?f=10&t=50834

MapCore Contest Forum (have to dig to view some of the .aas issues)
http://www.mapcore.org/forum/31-mapcores-quake-3-15th-anniversary-contest/

Similar issues:
https://github.com/TTimo/GtkRadiant/issues/264
https://github.com/TTimo/GtkRadiant/issues/265

**Comment by TTimo** [comment]
We rely on another project to maintain the BSPC source. I need to dig it up, can't find any info in our repository.

**Comment by TTimo** [comment]
Ok I found it, we have been using https://github.com/bnoordhuis/bspc - @QBall147 seems to have his hand in it.

**Comment by TTimo** [comment]
Did the addition of QL support break backwards compat to Q3? @QBall147 any insight on that?

**Comment by TTimo** [comment]
Check new build - has bspc.exe included https://s3.amazonaws.com/gtkradiant/GtkRadiant-1.6.5-20151224.zip

**Comment by TTimo** [comment]
more bspc fixes went into the latest 1.6.5 update
please report on the status of this - I will be closing this soon if there is no feedback
