### ISSUE TITLE
radiant.exe crashes on startup

### ISSUE THREAD

**Issue by OrangeOz** [TTimo/GtkRadiant#285]
I've clearly done something wrong and this may have been posted before, sorry.
I use windows 7 64 bit, I don't have quake 3 or anything like that, I wanted to make something for Return to Castle Wolfenstein.

Can anyone help? Thanks.

**Comment by ensiform** [comment]
Do you have the appropriate Visual C/C++ Runtime installed for 32 and 64 bit?

**Comment by OrangeOz** [comment]
Yes, I have the correct one, I re-installed just to be sure.

**Comment by OrangeOz** [comment]
Don't worry, I realized I didn't install it correctly, I put the CONTENTS of 'GtkRadiant-1.6.4' into a folder in program files rather than putting the actual 'GtkRadiant-1.6.4' folder into it.

Either that or just a re-install.
