### ISSUE TITLE
Gtk fails to execute devmap and run engine on Windows 10

### ISSUE THREAD

**Issue by thunderpwn** [TTimo/GtkRadiant#295]
Hey I migrated to windows 10 professional today from windows 7 and have been testing programs and games.
Only fault I can find is this:
[code]
Running engine...
G:\Program Files (x86)\Wolfenstein - Enemy Territory\ET.exe +set sv_pure 0 +devmap saigon
Failed to execute the following command: G:\Program Files (x86)\Wolfenstein - Enemy Territory\ET.exe+set sv_pure 0 +devmap saigon[/code]

I will investigate a bit further and see if it can be something with permission on Win10

**Comment by thunderpwn** [comment]
ok, I set it to comabillitymode for win 7 and run as administrator and it works :)

**Comment by Mateos81** [comment]
You should install older games out of Program Files, it's probably because of this :)

**Comment by thunderpwn** [comment]
I dont have it there...
