### ISSUE TITLE
Entity icons (gtk3)

### ISSUE THREAD

**Issue by Pan7** [TTimo/GtkRadiant#304]
There is a new feature for the 2d RMB click popup menu. It allows to show icons in front of the entity names (classnames).
I made a couple icons for q3a.
http://ws.q3df.org/files/entity_icons.zip
But right now the path for these icons is bad, it should probably use the mod folder of a game.

**Comment by ensiform** [comment]
Can these be backported to gtk2?

**Comment by Pan7** [comment]
Its already added.

**Comment by ensiform** [comment]
My bad, didn't see that.
