### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by RealAnatel** [TTimo/GtkRadiant#307]
Just seems to crash the q3map2.exe when I compile for test with .bsp 

https://www.dropbox.com/s/cbs3zv5kpyp564y/crypt.rar?dl=0 ALL THE MAP FILES

**Comment by ensiform** [comment]
q3map.exe or q3map2.exe

**Comment by RealAnatel** [comment]
I think you know its a typo and I meant q3map2.exe 

REALLY?

**Comment by Mateos81** [comment]
There are still people out there using Q3Map... @Pan opened a pull request fixing this I believe (#308).

**Comment by RealAnatel** [comment]
I have no idea what this means !! Or what to do with this info.

it wont load in quakelive and when I try load it in wolfcam it says map has no nodes.

Pan had another issue : [20:04] it couldn't compile a map because it creates a broken proj file for me

[20:04] dunno if you have the same problem

**Comment by RealAnatel** [comment]
I installed it all again on the laptop and it still did it.
I downloaded the files above from this web page, it still crashed the q3map2.exe

**Comment by 0bsidian** [comment]
Have you tried compiling one of the sample maps? Does it give you the same crash?

Any errors in the log files? At what point does it fail?

**Comment by RealAnatel** [comment]
https://youtu.be/5KeFH6TzR_M

**Comment by Pan7** [comment]
It doesn't crash for me but your map (file) is somehow broken. Everything is a func_door.

**Comment by RealAnatel** [comment]
Oops! it seems to be all the floors and walls maybe if I remove them.

**Comment by Pan7** [comment]
Select the func_door and ungroup it.

**Comment by RealAnatel** [comment]
its fine I am almost done :P 

It looks better too...
