### ISSUE TITLE
Remove STLPort

### ISSUE THREAD

**Issue by ensiform** [TTimo/GtkRadiant#310]
I really don't think its necessary anymore...  VS2010 is pretty stable stl wise and now 2013 and 2015 have lots of the C++11/14 additions which are both free.

Should probably make sure to use `std::` everywhere though instead of having to add using namespace std;

Note: 2015 currently will not compile.  With or without stlport. libintl breaks C io functions in some of the projects.

**Comment by TTimo** [comment]
Will review pull requests

**Comment by ensiform** [comment]
it would seem synapse must be replaced with a simpler plugin interface more akin to 1.5/netr before this is possible.  The usage of "stl" in the synapse api causes problems with debugging.

**Comment by TTimo** [comment]
So you are saying that the synapse code uses STL features that are supported by STLPort, but not by default MSVC STL support?

**Comment by ensiform** [comment]
No, I am saying that STLPort does not use things like custom allocators/std::allocator<> and other complex stuff.  Which real STL does.  Not really sure.  The vector usage in the public interfaces triggers allocator being not linked in during debug with STL being used vs STLPort.

Doing quick search reveals that its technically not guaranteed/supposed to work or use STL across dll boundaries.  So whatever STLport is doing, is avoiding something.  Don't ask me why it currently works in Release build though with STL.

**Comment by TTimo** [comment]
You are basically uncovering the reasons why STLPort was used in the first place, and why possibly we should continue to use it.

**Comment by ensiform** [comment]
I guess.... Using real STL would make more sense when possible.

**Comment by ensiform** [comment]
It seems impossible to make stlport actually compile at this point.  What's the newest VS version you were able to compile it with?

**Comment by TTimo** [comment]
It's gone from master by now. Closing.
