### ISSUE TITLE
Radiant 1.6.5 current issues

### ISSUE THREAD

**Issue by QBall147** [TTimo/GtkRadiant#332]
A few missing things from the latest test build

Missing q3map2 x64
Missing bspc
(some more QL game pack changes for me to check in)

probably a bunch of other stuff ^^

**Comment by TTimo** [comment]
- For q3map2 x64 we need a 64 bit binary of the new libxml.
- BSPC I had to track down the source - https://github.com/TTimo/bspc. Going to add a git clone to the scons target=setup at least.

Should look into reviving automated/scripted build machine.

**Comment by TTimo** [comment]
https://s3.amazonaws.com/gtkradiant/GtkRadiant-1.6.5-20151224.zip should cover those issues

@QBall147 unless you have other items, let's close this one?

**Comment by thunderpwn** [comment]
MSVCP140.dll is missing, cant start it...

**Comment by 0bsidian** [comment]
Sounds like you don't have the Visual C++ Redistributable 2015 installed on your system. This is always a separate download. Get it here (Note: if running 64-bit OS, you'll need to install BOTH 32 and 64-bit files):

https://www.microsoft.com/en-ca/download/details.aspx?id=48145
