### ISSUE TITLE
The bspc tool is missing support for QuakeLive-format AAS files

### ISSUE THREAD

**Issue by dfsp-spirit** [TTimo/GtkRadiant#333]
While it is possible to convert a Quake 3 Arena (Q3A) bsp file for use in QuakeLive (QL), it is currently not possible to get an AAS file (bot support) using any mapping tool.

Currently, the only option to get the AAS file is to hex edit it manually (according to rumours at Quake3World, see below).

It would be desirable to have an option to convert both the bsp and aas files to the current QL format. This would enable many people to publish their Q3A maps on the QL workshop, making a large number of great quality Q3A maps from the last decade available for QL.

References: 
Thread at Q3W -- http://www.quake3world.com/forum/viewtopic.php?f=10&t=51522
Thread at SteamCommunity -- http://steamcommunity.com/app/282440/discussions/0/490124466453397402/

**Comment by 0bsidian** [comment]
Duplicate issue:

https://github.com/TTimo/GtkRadiant/issues/282

**Comment by TTimo** [comment]
Closing dupe, thanks for the report please follow the other issue.
