### ISSUE TITLE
Tagged releases or source tarballs

### ISSUE THREAD

**Issue by Mailaender** [TTimo/GtkRadiant#334]
would really help package this for Linux distribution. https://icculus.org/gtkradiant/downloads.html only gives binaries and says latest version is 1.6.4, but https://github.com/TTimo/GtkRadiant/releases shows just the 1.5 version.

**Comment by TTimo** [comment]
Yeah we should do a better job at that

**Comment by danfe** [comment]
Why close if it's still not fixed?
