### ISSUE TITLE
misc_model cannot be easily selected if missing model destination

### ISSUE THREAD

**Issue by 0bsidian** [TTimo/GtkRadiant#336]
1. Right-click, misc_model (model selection dialog pops up).
2. Click cancel.
3. Deselect currently selected empty misc_model widget.
4. You are now unable to re-select the misc_model widget. Only way to do so is to create a brush and use "select inside", etc.

The same occurs if you open a map with missing model files.

The problem is that the misc_model widget has no dimensions so it can't be selected.

**Comment by ensiform** [comment]
I looked at the null model box code from 1.5 and netr and I don't see an easy way to backport it to 1.4/1.6 codebase. :/  Its confusing to say the least.

**Comment by Mateos81** [comment]
Duplicates https://github.com/TTimo/GtkRadiant/issues/28

Working on it: https://github.com/Mateos81/GtkRadiant/commit/30277762436a37ddd0e38ce820ef18759770570d
