### ISSUE TITLE
Map Info and Entities dialogs are larger than both screens on dual monitor setup

### ISSUE THREAD

**Issue by deedoubleu** [TTimo/GtkRadiant#339]
http://imgur.com/a/ED25H
Map Info almost fits, while Entities twice as big.

**Comment by Pan7** [comment]
Can you test the latest version of Radiant?

**Comment by deedoubleu** [comment]
1.6.5 (apr22 2017) still has it.

**Comment by Pan7** [comment]
Are you using Windows or Linux?

**Comment by deedoubleu** [comment]
Win7 SP1 x64
any additional info I can provide?

**Comment by Pan7** [comment]
Does it store the position and size If you change the windows?
Both "Map Info" and "Entity List" use the load_window_pos function
https://github.com/TTimo/GtkRadiant/blob/master/radiant/gtkmisc.cpp#L112
here
https://github.com/TTimo/GtkRadiant/blob/master/radiant/gtkdlgs.cpp#L929
https://github.com/TTimo/GtkRadiant/blob/master/radiant/gtkdlgs.cpp#L1256

**Comment by deedoubleu** [comment]
It does. Also remembers it between sessions.
That solves it, thank you.
