### ISSUE TITLE
Update mapcoordsmins and mapcoordsmaxs (Q3map2) 

### ISSUE THREAD

**Issue by osfpsproject** [TTimo/GtkRadiant#344]
For many people, it's probably unclear that the area to mark out needs to be cube-shaped. This was probably not an issue for quake 3 (as those maps were man-to-man, arena-style maps) but for many games (like militaryforces), it means that a lot of the area marked out can't be used (as the maps are rectangular in shape), so this means efficiency is worse than it could be.

I thus propose to allow making it rectangular, which will also mean you'd need to make more mapcoords; ie: mapcoords_topleft mapcoords_topright mapcoords_bottomleft mapcoords_bottomright

Another thing is that this "outer mapcoords barrier" one needs to put in should best also automatically create a leakage-proof container (so people will no longer need to make a skybox that is perfectly closed on all sides. For those that make a plain rectangle and then hollow it out, it's often not an issue, but those that make it custom-made, and also use the bottom terrain brush as the bottom skybrush, it can avoid a lot of trouble.

Perhaps that an even more convenient way would be to just have people add a func_ to all sides of the skybox, and have q3map2 immediately identify these brushes with the func_ as the outer mapcoords barrier. I guess that this way, it could possibly increase efficiency even more, as the Z-axis range is also limited, so less needs to be computed. If need be, it can be made to automatically create the following mapcoords from these func_ equipped brushes: mapcoords_topleft_upper mapcoords_topleft_lower mapcoords_topright_upper mapcoords_topright_lower mapcoords_bottomleft_upper mapcoords_bottomleft_lower mapcoords_bottomright_upper mapcoords_bottomright_lower (the _upper coords hereby containing the upper Z-axis coords, and the _lower ones containing the lower Z-axis coords; all mapcoords then have 3 coordinates instead of 2, so x, y, z instead of x, y )

**Comment by TTimo** [comment]
A quick check around q3map2 source code and Wolf ET source code shows that this mapcoordsmins stuff is all engine side and specific to ET (possibly derived engines), so I don't think any of this can be satisfied by the tools.
