### ISSUE TITLE
.mtl support by netradiant and MF2 game engine

### ISSUE THREAD

**Issue by osfpsproject** [TTimo/GtkRadiant#347]
.mtl's (used for coloring .obj models) are currently not supported by netradiant or the MF2 game engine. So, at present, neither netradiant nor the MF2 engine is able to display any colors of the obj models (used in the terrain, or even on player models -in combination with a specified color per mesh group in the model-).

**Comment by ensiform** [comment]
I'm confused.  Does netrad support this already and you want it in gtkrad or are you thinking this is the place to request features for netrad too?

**Comment by osfpsproject** [comment]
I wasn't sure this was the place to request netradiant functions too (there is https://gitlab.com/xonotic/netradiant/issues but that's on gitlab, and there's divVerent's netradiant github site (https://github.com/divVerent/NetRadiant) -which hasn't been updated for ages- itself forked from TTimo's radiant branch, so posted it both at gitlab and github. If not applicable for this github site, then disregard

**Comment by Mateos81** [comment]
Yes, but the Xonotic repo is bound to this one: https://github.com/xonotic/netradient
Itself a fork of divVerent fork :) Just use the GitLab for NetRadiant and this GitHub for GtkRadient, they're different projects (Gtk is based on 1.4 and Net on 1.5).

**Comment by TTimo** [comment]
Yeah it looks like you picked NetRadiant as your editor of choice for MF2, so I don't feel GtkRadiant or GtkRadiant's q3map2 branch particularly needs to be involved on there.

If general bug fixes were coming in as pull requests for us too then we would assess them, but in the current situation I don't think it makes much sense for us to have those issues in our tracker. Sorry to cause you extra work by having you enter those in the first place, was a misunderstanding.
