### ISSUE TITLE
Crash on rendering model with _remap key

### ISSUE THREAD

**Issue by SpaghettiMBII** [TTimo/GtkRadiant#350]
Version: GtkRadiant 1.6.4 Dec 13 2013
Platform: Windows 10 x64
Game: Jedi Academy

Radiant crashes to the desktop when trying to render model entities that contain a _remap key. Such maps can be loaded if models are filtered but crash the instant the filter is turned off. I have attached a .map where this occurs (multiple misc_model with _remap).

[example.zip](https://github.com/TTimo/GtkRadiant/files/258500/example.zip)

**Comment by TTimo** [comment]
Please reproduce on latest 1.6.5 release. We are not making fixes to older releases.

FYI this is current build:

https://s3.amazonaws.com/gtkradiant/GtkRadiant-1.6.5-20160424.zip - you need MSVC runtime too:  https://www.microsoft.com/en-ca/download/details.aspx?id=48145

**Comment by ensiform** [comment]
The site still lists the old one btw.

**Comment by TTimo** [comment]
Duplicate this has been fixed in latest

**Comment by SpaghettiMBII** [comment]
The crash does not occur on that build and the remaps are displaying correctly in the 3D view.

**Comment by TTimo** [comment]
yay!
