### ISSUE TITLE
Possible Licesne Violation

### ISSUE THREAD

**Issue by Arefu** [TTimo/GtkRadiant#356]
Treyarch (http://www.treyarch.com/)

Way back in 2008+/- a year released Mod tools for Call of Duty: World at War.
I did a bit of digging around, and I have found out that they're using Radiant as a base platform to make their version of Radiant. However, since this is licensed under GPL they have to provide Source Code etc.

I have found no possible way to request it. So me in my pissy annoying ways came here and all I ask is, Is anything going to be done?

**Comment by ensiform** [comment]
Treyarch and Infinity Ward do not use anything of GTKRadiant.

They have a licensed version of Q3Radiant and remade that into their own with the Q3 License they rightfully own at Activision.
