### ISSUE TITLE
Link to Mac version

### ISSUE THREAD

**Issue by CircaCitadel** [TTimo/GtkRadiant#361]
I had reported an issue with Radiant awhile back [here](https://github.com/TTimo/GtkRadiant/issues/279) and it worked fine. The site was updated with the new link. Now I'm reinstalling it and the link is broken.

The new file was named GtkRadiant-1.6.4-1.dmg so I tried taking out the -1 and that downloaded, but it's the old version that doesn't open properly.

Can that link be fixed so I can get that fixed version?

**Comment by TTimo** [comment]
Try this build: http://quetoo.org/files/GtkRadiant-1.6.5.dmg
Agreed, we need to update the site.

**Comment by CircaCitadel** [comment]
Yep, that worked. Thanks.

**Comment by TTimo** [comment]
Please report if the build works. @jdolan  will want to know

**Comment by CircaCitadel** [comment]
Well, I was having trouble with 1.6.4, which is why I was reinstalling it. Can't figure out if it's an issue on my end or with the build(s). Something about not finding textures properly when compiling. I can make a new issue for it if that's preferred.

**Comment by 0bsidian** [comment]
Cool. Thanks for the link. Will update site soon, though I'm not sure if we have a timeframe for a 1.6.5 release.

**Comment by CircaCitadel** [comment]
Looks like it's good to go from what I can tell. :)

**Comment by m-decoster** [comment]
I'm having some issues with this build on Mac OS X El Capitan. I get the error 'Synpase server initialization failed', here's the radiant.log file:

```
Started logging to /Users/mathieu/.radiant/1.6.5/radiant.log
Today is: Sat Aug 13 15:04:28 2016
This is radiant '1.6.5' compiled May  7 2016
http://icculus.org/GtkRadiant/
Wrote XML property file '/Users/mathieu/.radiant/1.6.5/global.pref'
game name            : 'Quetoo'
game file            : 'quetoo.game'
game path            : '/Users/jdolan/Coding/GtkRadiant/install/installs/QuetooPack/game/'
base game            : 'default'
engine path          : '/usr/local/share/quetoo/'
executables path     : '/usr/local/bin'
engine               : 'quetoo'
shaderlist           : 'scripts/shaderlist.txt'
caulk shader         : 'textures/common/caulk'
prefix               : '.quetoo'
default texture scale: 0.25
single eclass load   : No
patches supported    : No
Wrote XML property file '/Users/mathieu/.radiant/1.6.5/global.pref'
Reloading global prefs from file
Opened XML property file: '/Users/mathieu/.radiant/1.6.5/global.pref'
Opened XML property file: '/Users/mathieu/.radiant/1.6.5/quetoo.game/local.pref'
OpenGL not ready - postpone texture compression capability check
OpenGL not ready - postpone ATI bug workaround setup
Loading GL library: /Applications/GtkRadiant.app/Contents/Resources/lib/libGL.1.dylib ...Done.
'/Applications/GtkRadiant.app/Contents/Resources/install/global.xlink' not found / parse failed
'/Users/jdolan/Coding/GtkRadiant/install/installs/QuetooPack/game/game.xlink' not found / parse failed
loading synapse XML config file '/Users/jdolan/Coding/GtkRadiant/install/installs/QuetooPack/game/synapse.config'
'/Users/jdolan/Coding/GtkRadiant/install/installs/QuetooPack/game/synapse.config' invalid/not found
Synpase server initialization failed (see console)

errno: No such file or directory
An unrecoverable error has occured.
Would you like to edit Preferences before exiting Radiant?Shutting down GL ...Done.
Closing log file at Sat Aug 13 15:04:31 2016
```

**Comment by jdolan** [comment]
Oh, geez. Looks like that build is referencing my working copy path for some reason. That's actually kinda curious. @TTimo can you refresh my memory as to why that might happen?

**Comment by jdolan** [comment]
Uploading a new version that will hopefully fix this issue. Please re-download in about an hour. Thanks, and apologies for the busted build!

**Comment by m-decoster** [comment]
I'm assuming I've now downloaded the new version (it says last edited about 1.45h ago), still the same issue.

**Comment by jdolan** [comment]
Please open `GtkRadiant.app/Contents/Resources` and delete the `install/games/quetoo.game`. It must be bundling my local configuration for Quetoo.

**Comment by jdolan** [comment]
In other words, try this at the Terminal:

`rm /Applications/GtkRadiant.app/Contents/Resources/install/games/quetoo.game`

**Comment by m-decoster** [comment]
Thanks, that fixed it!

**Comment by jdolan** [comment]
I'm uploading a fixed build right now.
