### ISSUE TITLE
Mouse Pointer Gets Stuck In 2D viewport

### ISSUE THREAD

**Issue by cityy** [TTimo/GtkRadiant#37]
Sometimes when I'm in edge editing mode in one of the 2d viewports and click mouse2 to move the camera the pointer gets stuck even when I release the button. I have only noticed the issue when I'm in edge editing mode. I'll pay more atention to it in future to give further details on the issue. 

Edit: This now happened to me in normal editing mode too. It happens in all 2d viewports.

**Comment by Pan7** [comment]
This issue is really old and probably gone. Just create another one if the problem still exists.
