### ISSUE TITLE
No FreeBSD support

### ISSUE THREAD

**Issue by scriptinfu** [TTimo/GtkRadiant#378]
GtkRadiant does not compile on FreeBSD: 

```
In file included from libs/synapse/synapse.cpp:28:0:
libs/synapse.h:65:4: error: #error unknown architecture
   #error unknown architecture
```

Any help getting this to work is much appreciated.

**Comment by illwieckz** [comment]
Hi, can you try out my FreeBSD branch?

- [illwieckz/GtkRadiant/tree/freebsd](https://github.com/illwieckz/GtkRadiant/tree/freebsd)

See PR #565 about it, badly I was not able to run radiant but as stated on that other thread the FreeBSD setup I used seems inconsistent, so I don't know if it's radiant's fault or FreeBSD's fault. It builds though.

**Comment by illwieckz** [comment]
Note: I updated my branch and it now runs but I was only able to test configuring games etc, not yet displaying the 3d stuff because I don't have direct rendering yet. Perhaps it works, I just haven't any way to test it.

**Comment by illwieckz** [comment]
It works:

[![GtkRadiant on FreeBSD](http://dl.illwieckz.net/b/gtkradiant/20170830-221127-000.gtkradiant-freebsd-mapping.png)](http://dl.illwieckz.net/b/gtkradiant/20170830-221127-000.gtkradiant-freebsd-mapping.png)
[![GtkRadiant on FreeBSD](http://dl.illwieckz.net/b/gtkradiant/20170830-221744-000.gtkradiant-freebsd-quake3.png)](http://dl.illwieckz.net/b/gtkradiant/20170830-221744-000.gtkradiant-freebsd-quake3.png)

**Comment by jdolan** [comment]
Fuckin' awesome, man. Nice work.

**Comment by illwieckz** [comment]
See also [NetRadiant!75](https://gitlab.com/xonotic/netradiant/merge_requests/75), the merge request that fixes NetRadiant building on FreeBSD too:

[![NetRadiant on FreeBSD](http://dl.illwieckz.net/b/netradiant/screenshots/freebsd/20170831-011805-000.netradiant-freebsd-xonotic.png)](http://dl.illwieckz.net/b/netradiant/screenshots/freebsd/20170831-011805-000.netradiant-freebsd-xonotic.png)

**Comment by TTimo** [comment]
Good stuff!
