### ISSUE TITLE
right mouse click move broken in 2d view and camera

### ISSUE THREAD

**Issue by TTimo** [TTimo/GtkRadiant#380]
right click mouse move will only move the 2d view downwards, at high speed
right click mouse move in the camera view will quickly move the view to look straight down

there are several sort of similar issues that have been reported over the years
#237, #111, #149

seems I have repro now for some reason ..

**Comment by bugdnd** [comment]
Same problem, but I change windows user, and here we go - gtk works fine!
But for me, it is not a solution...

**Comment by TTimo** [comment]
Should be fixed in latest build - see website

**Comment by TTimo** [comment]
This has been broken again by later changes apparently.

**Comment by TTimo** [comment]
nevermind, see issue #531

**Comment by sneakin** [comment]
Must still be broken. Couldn't figure out how to scroll the 2d view short of dragging something to an edge and OMG too fast!

**Comment by sneakin** [comment]
Built from github for Linux. On a 2d view: right click, right click + drag, ctrl+right click, shift+right, ...nothing starts panning the view.

**Comment by sneakin** [comment]
Poking around: adding a check to see if m_nButtonState == 0 before assigning it in XYWnd::XY_MouseDown gets right click + drag panning working. It's a hack for sure. Seems like GTK fires an event with just the left button flagged when dragging starts.

Related to this drag bug in another GTK application? https://github.com/mate-desktop/caja/issues/753

**Comment by sneakin** [comment]
It's a touchpad problem! Right click + Thinkpad pointer stick works. Touching the touchpad causes a left button pressed event which resets XYWnd's button state. Even with the condition on assignment, adjusting my finger to a new spot on the touchpad would enter the brush drawing mode.
