### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by AgniChim** [TTimo/GtkRadiant#383]
Every time i start up radiant for black ops 3 and go to attempt to make a map i am stuck on the screen that said "raddiant black edition" "initializing graphics system" and it will just stay there and not do anything shortly after it will say its not responding. ive tried to leave it alone for hours and still nothing is there a fix for this or will it just not work for me?

**Comment by TTimo** [comment]
Radiant black edition for black ops 3 is not related to the GtkRadiant project.
Please see our website for the list of games supported by GtkRadiant.
