### ISSUE TITLE
Problems with compiling map with alot .ase models

### ISSUE THREAD

**Issue by newsource-trem** [TTimo/GtkRadiant#389]
Hi guys!

Im have problems and want to tell you about that, why im saying that? Because NetRadiant's q3map2 doesn't have this problem.

So, im have map, there 710 entities, 99% of them is .ase models,  
latest NetRadiant q3map2 doesn't have that problems, but gtkradiant 1.6.5 one is.

So simple map with few .ase they compiles fine, but with 700+ .ase...they just skips following steps:
--- AddTriangleModels ---
--- AddEntitySurfaceModels ---
--- FilterDetailBrushesIntoTree ---
----- FogDrawSurfs -----
--- SubdivideFaceSurfaces ---
--- FixTJunctions ---
--- ClassifyEntitySurfaces ---
--- TidyEntitySurfaces ---
--- MakeEntityMetaTriangles ---
--- TidyEntitySurfaces ---
--- TidyEntitySurfaces ---
--- SmoothMetaTriangles ---
--- MergeMetaTriangles ---
--- FilterDrawsurfsIntoTree ---
--- FixBrushSides ---
--- EndModel ---
--- EmitMetaStats ---
--- ProcessAdvertisements ---
--- EndBSPFile ---
--- WriteSurfaceExtraFile ---

q3map2 is just skips those steps and doing next step of compilation, but as i said, netradiant one is doesn't skip that

**Comment by ensiform** [comment]
Apples and oranges.  1.6 forked from 1.4 branch and NetRadiant is a fork of 1.5 rewrite.

Have you tested 1.6.5 in case? 1.6.4 is technically older, but I'm sure its still going to have same issue unless it was fixed with recent patches not yet released.

**Comment by newsource-trem** [comment]
Hmmm...thanks you for information, i will try.

**Comment by Mateos81** [comment]
What game is it for? Could you please supply a test map to check, if it's possible?

**Comment by newsource-trem** [comment]
Tremulous. em...map. oki, i'll give you it soon as possible

**Comment by 0bsidian** [comment]
Tremulous isn't even supported by GtkRadiant 1.6. I don't know if the version of Q3map2 that ships with 1.6 retains the ability to compile Tremulous maps, but it certainly isn't something being tested. See here for a list of supported games:

http://icculus.org/gtkradiant/developers.html#gamepacks

**Comment by ensiform** [comment]
Q3map2 does still support trem: https://github.com/TTimo/GtkRadiant/blob/master/tools/quake3/q3map2/game_tremulous.h

**Comment by 0bsidian** [comment]
Cool. But if he's compiling with GtkRadiant's build menu, that will not work. He will need to compile using his own batch file or with other tools to invoke Q3Map2.

**Comment by Garux** [comment]
> is x32, and compilation VERY LONG...and there is no q3map2 x64
-It is ok to take time (depends on models complexity); also the ase loader is not superfast itself (is told to be faster in bloodmap fork)
-x64 wont gain too much speed; was about -30% in one of my tests
-can compile x64 netradiant for windows; works and seems stable (i can compile, if you want)

**Comment by newsource-trem** [comment]
Yes, compile please x64 netradiant for me :)

**Comment by Garux** [comment]
Done!
https://goo.gl/gBQSGC

**Comment by TTimo** [comment]
Closing this - GtkRadiant does not support Tremulous. There is no indication of anything actually wrong with GtkRadiant.
