### ISSUE TITLE
HalfLife support

### ISSUE THREAD

**Issue by Tarik02** [TTimo/GtkRadiant#396]
Where i can get GtkRadiant with HalfLife 1 support for linux kubuntu x64?

**Comment by Mateos81** [comment]
Classic: HL/Q2/Heretic2: http://icculus.org/gtkradiant/downloads.html

I believe there's still HL stuff in the current version, could be re-enabled, if some volunteer would like to support it?

**Comment by Tarik02** [comment]
@Mateos81, this link is for windows. I found other editor for the halflife maps.
