### ISSUE TITLE
Synapse Server initialization failed

### ISSUE THREAD

**Issue by cityy** [TTimo/GtkRadiant#409]
I've had the following problem trying to set up Radiant 1.6.5 170225 for QL on windows 10:

![capture](https://cloud.githubusercontent.com/assets/1555990/23339435/b50c6ce8-fc22-11e6-8a7b-e473edc07240.JPG)

Log File:
```
'C:/Users/Ferdinand List/Software/GtkRadiant-1.6.5-20170225/global.xlink' not found / parse failed
'C:/GtkRadiant/GtkRadiant/install/installs/QLPack/game/game.xlink' not found / parse failed
loading synapse XML config file 'C:/GtkRadiant/GtkRadiant/install/installs/QLPack/game/synapse.config'
'C:/GtkRadiant/GtkRadiant/install/installs/QLPack/game/synapse.config' invalid/not found
Synpase server initialization failed (see console)

GetLastError: The system cannot find the path specified.
```

I've tried locating the files radiant is looking for manually. The file _global.xlink_ is not in place anywhere. The other files are there but the paths are different. 
GtkRadiant-1.6.5-20170225\installs\QLPack\game\game.xlink
GtkRadiant-1.6.5-20170225\installs\QLPack\game\synapse.config

Is anyon having the same issue?

-cityy

**Comment by cityy** [comment]
Hey TTimo,
thanks for the quick reply. I got it fixed. Maybe if you have a free minute you could update the pack with a clean configuration so that rusty folks like me dont get confused.

Cheers!

**Comment by TTimo** [comment]
Yeah - I don't package new releases often enough to have a reliable process there :)
We'll leave this open in case someone else has the same problem.
May have to do another update if more folks get around to test it up.

**Comment by Pan7** [comment]
Getting this error when i use the 1.6.4 plugins/modules with 1.6.5.

**Comment by TTimo** [comment]
We've released updates that have addressed this.
