### ISSUE TITLE
q3map_surfacelight keyword is ignored

### ISSUE THREAD

**Issue by frederickbrown** [TTimo/GtkRadiant#417]
q3map_surfacelight keyword is ignored in newly written shaders, resulting in a surface that just appears as a regular surface without emitting any light.  So far I know this only happens in the 32 bit version of q3map2.  How would I get VS 2015 to compile the 64 bit version to test?

**Comment by Mateos81** [comment]
Have you run a Flush & Reload shaders? If you've restarted Radiant meanwhile, it has reloaded the files, so in order to test this, have the shader with the line commented out, start Radiant with your map, then edit the shader and perform the command through the Textures menu IIRC (I don't have Radiant at work :P).

If you select x64, it should build the x64 version of Q3Map2.

**Comment by TTimo** [comment]
32 bit radiant can run the 64 bit q3map2 - that's probably configured in preferences

**Comment by frederickbrown** [comment]
Just to be sure I tried flushing & reloading the textures. the surface light keyword is still being ignored. Note this only happens with custom written shaders. The surface light shaders that are in the pk3 files still work. 

The 64bit executable for the x64 folder is failing to get built. The program defaults to using that, and when one attempt to compile a map, there is an error message about radiant failing to find the q2map2 in the x64 folder. Then if that preference is unchecked, the 32 bit executable runs just fine. 

I tried to do a transplant of q2map2 from a version of radiant that did compiled my custom surface light shaders into the version of radiant that failed to do so, and the problem remained. So, it might be somewhere other than in q2map2.

**Comment by ensiform** [comment]
Does your shader exist in shaderlist.txt, if not it may not be detected as a shader.

**Comment by frederickbrown** [comment]
Yes.

**Comment by ensiform** [comment]
Well, those are both based on the 1.5 branch.  If other shaders that work besides yours that uses surfacelight, it sounds more likely that it isn't detecting the shader either in radiant or q3map2.

**Comment by frederickbrown** [comment]
Yes, that's my conclusion as well.

**Comment by 0bsidian** [comment]
Do not include the .shader extension in the shaderlist.txt file. It should be just listed like:

base
gothic
liquids
skies
blah

**Comment by frederickbrown** [comment]
What part of "both GtkRadiant 1.5 and Ingar's NetRadiant compile my custom surface light shaders as expected using the same game files and same game directories" are you guys missing.
[shaderlist.txt](https://github.com/TTimo/GtkRadiant/files/818105/shaderlist.txt)

**Comment by ensiform** [comment]
And which shader file are they in because that looks like only stock shader files.

**Comment by frederickbrown** [comment]
Do you mean the list in shaderlist.txt?

**Comment by Garux** [comment]
What i see is, that your most likely to be meant custom shader

**Comment by frederickbrown** [comment]
Thank you for that.  I just uncommented and tried it again and it worked. 

I was having trouble with this and trying it on a number of different gtkradiant and netradiant versions in a variety of ways. I guess lost track of the state of the shader with with this last version of gtkradiant which I wasn't using because of the view port problem. 

So, it works and the problem was a non-problem with this version. That's a relief. 

I'll get back to mapping now... :)
