### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jdolan** [TTimo/GtkRadiant#434]
The repository really should contain a README.md that explains the build process. This would be particularly valuable because GtkRadiant's build is so custom / homegrown. New users shouldn't have to first study `config.py` before being able to build Radiant locally.

**Comment by ensiform** [comment]
Having some visible information for users too besides on the radiant site would be helpful as well.  Build status, links to non-Windows ports etc.

**Comment by ensiform** [comment]
https://github.com/jehna/readme-best-practices/blob/master/README-default.md

https://github.com/fraction/readme-boilerplate

**Comment by ensiform** [comment]
Any progress on this front yet?

**Comment by TTimo** [comment]
You could write it and send a pull request..

**Comment by ensiform** [comment]
That would imply I actually know the necessary components for compiling etc.
