### ISSUE TITLE
Visual Studio 2017 support is broken until SCons supports it

### ISSUE THREAD

**Issue by ensiform** [TTimo/GtkRadiant#459]
More of a heads up for people upgrading on Windows.

SCons still has not pushed a full fix for 2017 support yet thus no release includes 2017 detection.

MS changed installation detection to use a COM application instead of relying on the registry information like previous versions which SCons was doing before.

**Comment by TTimo** [comment]
The Windows build only uses scons to pull in depedencies, it doesn't drive Visual Studio compilation. http://icculus.org/gtkradiant/documentation/windows_compile_guide/#compile

**Comment by ensiform** [comment]
Sure but even doing `scons` in the root directory causes it to fail to finish doing all the necessary steps grabbing the deps.
