### ISSUE TITLE
“scons -c” downloads game packs

### ISSUE THREAD

**Issue by illwieckz** [TTimo/GtkRadiant#477]
Running `scons -c` downloads game packs, which is not exactly the meaning of “cleaning”. :wink:

**Comment by illwieckz** [comment]
NB: I don't expect `scons -c` to clean game packs, so if someone wants to fix this, don't be zealous. :smile:

**Comment by Pan7** [comment]
How about a check here: https://github.com/TTimo/GtkRadiant/blob/master/config.py#L301
"if not env.GetOption('clean')"
