### ISSUE TITLE
Issue with textures on a Urban Terror map

### ISSUE THREAD

**Issue by suchacoder** [TTimo/GtkRadiant#495]
Hi there please help me, i'm new to this editor but i think this is like a bug or something. See while in the editor aplying textures i see them like this:  http://i.imgur.com/lb8BoAZ.png
But once in game testing the map i see the textures like this:  http://i.imgur.com/w36d0NB.jpg
Please help

shader:

//-----------------
// General textures
//-----------------

textures/ut4_chuck_b1/matrix
{
    qer_editorimage textures/ut4_chuck_b1/chars_1.tga
    q3map_globaltexture
    {
        map textures/ut4_chuck_b1/beam_multi.tga
        rgbGen identity
        tcMod scale 1 0.25
        tcMod scroll 0 -0.5
    }
    {
        map $lightmap
        blendfunc add
        rgbGen const ( 0.3 0.3 0.3 )
        tcGen lightmap
    }
    {
        map textures/ut4_chuck_b1/beam_single.tga
        blendfunc add
        rgbGen identity
        tcMod scroll 0 -0.2
    }
    {
        map textures/ut4_chuck_b1/beam_single.tga
        blendfunc add
        rgbGen identity
        tcMod scale -1 1
        tcMod scroll 0 -0.3
    }
    {
        map textures/ut4_chuck_b1/chars_all.tga
        blendfunc filter
        rgbGen identity
    }
    {
        animmap 1 textures/ut4_chuck_b1/chars_1.tga textures/ut4_chuck_b1/chars_2.tga textures/ut4_chuck_b1/chars_3.tga textures/ut4_chuck_b1/chars_4.tga
        blendfunc add
        rgbGen wave inversesawtooth 0 1 0 1
    }
    {
        animmap 2 textures/ut4_chuck_b1/chars_3.tga textures/ut4_chuck_b1/chars_4.tga textures/ut4_chuck_b1/chars_4.tga textures/ut4_chuck_b1/chars_1.tga textures/ut4_chuck_b1/chars_1.tga textures/ut4_chuck_b1/chars_2.tga textures/ut4_chuck_b1/chars_2.tga textures/ut4_chuck_b1/chars_3.tga
        blendfunc add
        rgbGen wave inversesawtooth 0 1 0.5 1
    }
}

textures/ut4_chuck_b1/gray_metal
{
    qer_editor_image textures/ut4_chuck_b1/gray_metal.tga
    {
    map textures/ut4_chuck_b1/gray_metal.tga
    }
}

//----------------
// Light entities
//----------------

textures/ut4_chuck_b1/bright_light
{
	qer_editor_image textures/ut4_chuck_b1/bright_light.tga
	surfaceparm nodamage
	surfaceparm nomarks
	{
	map textures/ut4_chuck_b1/bright_light.tga
	}
	{
	map $lightmap
	rgbGen identity
	blendFunc filter
	}
}

//---------
// Liquids
//---------

textures/ut4_chuck_b1/akuta_toxic
{
    qer_editorimage textures/ut4_chuck_b1/akuta_toxic.tga
    qer_trans 0.5
    q3map_globaltexture
    surfaceparm trans
    surfaceparm lava
    surfaceparm noimpact
    q3map_surfacelight 1500
    cull disable
    tessSize 64
    deformVertexes wave 250 sin 4 8 0.15 0.1
    {
        map textures/ut4_chuck_b1/akuta_toxic.tga
        tcmod scale 0.5 0.5
        tcmod scroll 0.2 -0.2
        tcMod turb 0.0 .25 0.0 .2
        blendFunc GL_ONE GL_ZERO
        rgbGen identity
    }
}

//-----
// Sky
//-----

textures/ut4_chuck_b1/sky
{
    qer_editorimage textures/ut4_chuck_b1/sky.tga
    surfaceparm noimpact
    surfaceparm nolightmap
    q3map_globaltexture
    q3map_lightsubdivide 256
    surfaceparm sky
    q3map_surfacelight 50
    q3map_sun 1 1 1 100 250 90
    skyparms env/ut4_chuck_b1/hive/hive 720 -
}

**Comment by Pan7** [comment]
Radiant, the compiler or the engine doesn't find your shader\shader file.
This often occurs if your map stuff isn't in the base folder.
You can compile your maps manually or with a batch script that is using your custom folders or you move everything into the base folder.

**Comment by 0bsidian** [comment]
Also, check shaderlist.txt and make sure your shader files are listed.

**Comment by suchacoder** [comment]
Thanks Obsdian, alredy solve my issue with mapping, Pan helped me on IRC quakenet #radiant, the problem was that i was mapping in '$HOME/mapping/q3ut4/' that was my base dir for Urban Terror, but q3map2 was searching my .shader file in '$HOME/.q3a/q3ut4/scripts'
even tho i specify on my .proj file that my base dir is in: '$HOME/mapping/q3ut4/'  q3map2 still looks for the .shader files on '$HOME/.q3a/q3ut4/scripts'  so i moved everything i had in '$HOME/mapping/q3ut4/'  and put it in  '$HOME/.q3a/q3ut4/'  and voila, all my troubles flew away, Thanks Pan <3

**Comment by ensiform** [comment]
You could have set -fs_basepath in q3map2 presumably to the root folder of where the urban terror bin was located.
