### ISSUE TITLE
Crash when Asus Sonic Studio is running

### ISSUE THREAD

**Issue by Aciz** [TTimo/GtkRadiant#536]
I'm not entirely sure if this belongs here/is an issue for GtkRadiant, but having Asus Sonic Studio open crashes the program when moving the camera (most of the time). I've gotten them to work at the same time few times, but I'm unable to reproduce the working scenario, it seems to happen completely randomly. I managed to get one crash dump yesterday, usually it just crashes without creating a dump file.

https://www.dropbox.com/s/l8tu9wg634s0359/GTKRadiant-1.6.5-20170805-150126.dmp?dl=0

Here's Event Viewer crash:

https://pastebin.com/31GC14pw

And a video showing the problem:

https://youtu.be/xlpyU-LAAIE

Can provide more info/do more testing if needed, but I'm not a programmer so please point me to right direction when investigating, if this is something that should/could be fixed on GtkRadiant side.

**Comment by Pan7** [comment]
What build of GtkRadiant 1.6.5 is this? 20170422?
Is it the download file GtkRadiant-1.6.5-20170422.zip?

**Comment by Aciz** [comment]
I was actually on February 25th build. Downloaded the newest one, and the same problem occurs.

**Comment by ensiform** [comment]
I wonder if this is similar to people experiencing random crashes on launch/during use with nvidia's geforce experience overlay related to game streaming/recording/screenshots ?

**Comment by Pan7** [comment]
The dump file doesn't show anything usefull. Might try to disable the Rivatuner Statistics Server Hooks.

**Comment by Aciz** [comment]
I have disabled the hook globally, it only hooks to specific applications. Regardless, disabled it completely and I'm still having the issue.

**Comment by Aciz** [comment]
This issue might have been caused by something in Windows itself (10 Pro x64). About a week ago I installed some bigger update, and this issue hasn't been happening since.
