### ISSUE TITLE
Fixed texture size tries to fit selected texture in viewpoint

### ISSUE THREAD

**Issue by Aciz** [TTimo/GtkRadiant#542]
GtkRadiant-1.6.5-20180806

This is a pretty hard issue to describe. When using the non-fixed size texture window, selecting a texture not fully visible will scroll the window down to the bottom of the texture. However the same thing seems to happen on fixed texture size. Even if the fixed size texture fits properly in the window, it still scrolls down as if the fixed layout wasn't in use.

Here's a video:
https://youtu.be/QGVsQZTmwnE

**Comment by Pan7** [comment]
Is the problem solved with the latest build?

**Comment by TTimo** [comment]
*bump*

**Comment by Aciz** [comment]
Yes it is.

**Comment by TTimo** [comment]
noice
