### ISSUE TITLE
Can't set default texture scale to 0,25 from menu

### ISSUE THREAD

**Issue by Aciz** [TTimo/GtkRadiant#547]
GtkRadiant-1.6.5-20180806

Previously you could set default texture scale with 6 decimal accuracy. With the latest build, in order to have any other than X,X default texture scale, you need to manually go to local.pref and edit "DefaultTextureScale".

**Comment by Pan7** [comment]
How much digits should it be?

**Comment by Aciz** [comment]
Previous versions allowed you to type a lot of numbers there, but it would only save it with 6 decimal accuracy to local.pref. So 7 numbers is probably a good amount. The most accurate default texture scale I imagine anyone would use is 0,125, so 7 should be plenty to set it to whatever value is desired.

**Comment by Pan7** [comment]
Only got it working properly with 6 digits.

**Comment by Aciz** [comment]
That's fine, the main issue is that when you work on higher resolution textures (1024x1024 for example) you usually want to set your texture scale to 0,25, which was problematic as it is now.
