### ISSUE TITLE
60 FPS and No window fading

### ISSUE THREAD

**Issue by SzczurMr** [TTimo/GtkRadiant#556]
Would it be advisable to insert / correct:

- minimum 60 frames per second in the 2d and 3d windows (as was the case with GTKRadiant 1.5 in the installation version)
- In the windows separate window disappears when I press the second (in GTK RAdiant 1.5 did not have this effect) It is very annoying   : - /

**Comment by ensiform** [comment]
Try not to compare 1.5 too much. It was the "redheaded stepchild" version of radiant.

Hopefully they can take a look for you to see if this is something that can be brought to 1.6 but no promises since the code is more like 1.4.

**Comment by SzczurMr** [comment]
https://youtu.be/7YauFdWmimA

**Comment by TTimo** [comment]
So since you are using the floating windows layout, can't you shrink the menu/icons toolbar to just be at the top? Then when you click on entities it will still be focusing up, but not over your 2D window?

**Comment by SzczurMr** [comment]
I can but at every start I have to set a new place, do not save window positions ...: /

**Comment by SzczurMr** [comment]
ok in the "radiant 2018-02-03" version saves the window state
thanks to a good job
