### ISSUE TITLE
GtkRadiant-1.6.5-20170820 crash at startup Nvidia Experience

### ISSUE THREAD

**Issue by Xian55** [TTimo/GtkRadiant#569]
Hello, i've just downloaded the latest version from the web. i ran with admin privileges.
I just wanted to open Jedi Outcast project from steam its clean installed.

Im using the latest Nvidia Experience program which has an game overlay function.
If its enabled, the GTKRadiant crashes after startup!

I've traced the error via Visual Studio
>	nvoglv32.dll!0ad8cc19()	Unknown

**Comment by TTimo** [comment]
Doesn't sound like GtkRadiant's fault then. Probably NVidia Experience was never tested against older OpenGL fixed function code and is broken.

**Comment by pureandclear** [comment]
You're seriously just brushing it off that casually? You know the Steam hardware survey shows that 85% of gamers use Nvidia graphics cards? Most of them probably have Geforce Experience installed. So you have a huge amount of the population that will get this crash, will probably never find this tiny Github issue telling them how to fix it(unless they trace it in a debugger), so guess what? They're going to just give up stop using Radiant. At least add a damn warning message or something! Your reaction is like if Radiant stopped working on Windows 10 altogether and you just closed the issue saying "well Microsoft probably broke it, shucks for all the Win 10 users out there, you're shit out of luck"

**Comment by Mateos81** [comment]
What features of that overlay do you want to use in Radiant? Can't it just be turned of for Radiant?
Should Radiant support any modern software with an overlay, or messing with the render of other programs? I don't think so...

**Comment by TTimo** [comment]
I run Windows 10 with an NVidia card and I don't experience this crash. In 3 months time nobody else has reported this which leads me to suspect it's either a user problem, or has been fixed by NVidia already.

**Comment by Xian55** [comment]
Make you sure that Experience overlay is [https://ibb.co/cXdHEG](enabled).

**Comment by Aciz** [comment]
I do not experience this crash either, Win 10 Pro x64. Running GTX 980 Ti with latest drivers, overlay enabled. I do not have instant replay enabled though, could it be that?

**Comment by pureandclear** [comment]
I do get this crash, 980Ti latest drivers. If I have overlay off, I don't crash. If I have overlay on, I crash.

**Comment by TTimo** [comment]
I wonder if we could detect the experience overlay enabled and abort early. I don't know if listing the DLLs injected in the process would be enough to tell if it's on.
