### ISSUE TITLE
Next Leak Spot doesn't work properly

### ISSUE THREAD

**Issue by Majki** [TTimo/GtkRadiant#57]
This function, under "Misc" menu seems to be broken. Instead of showing me next leak spot, it changes angle of camera of existing one.

**Comment by Mateos81** [comment]
Can't reproduce, it works fine here: the camera and 2D/3D views follow the red line from the leak end to the starting entity.
It does only change the angle of the camera when the line is vertical, or there's a turning point with an acute angle, but that looks like a normal behaviour?
