### ISSUE TITLE
when loading more than one VFS only one shaderlist.txt is read

### ISSUE THREAD

**Issue by illwieckz** [TTimo/GtkRadiant#573]
when loading more than one VFS only one `shaderlist.txt` is read (the last one iirc) and overrides all the other ones.

**Comment by TTimo** [comment]
What's a good test case for this though? Unvanquished + pk3dir support is the only setup that will initialize multiple VFS, correct?

**Comment by illwieckz** [comment]
unvanquished test case makes the issue very hard to ignore, but it's an issue for everyone: once the player put a shaderlist.txt in game homepath, it overrides the one provided by the game in engine path. Users can copy paste the one from game vendor to extend it, but if one day the game vendor decide to extend it too, the user will never notice it.

**Comment by TTimo** [comment]
Thanks, that clarifies the problem.

**Comment by illwieckz** [comment]
it's just a radiant issue, q3map2 [already loads them all](https://github.com/TTimo/GtkRadiant/blob/master/tools/quake3/q3map2/shaders.c#L1993-L2002):

```c
	/* we can pile up several shader files, the one in baseq3 and ones in the mod dir or other spots */
	sprintf( filename, "%s/shaderlist.txt", game->shaderPath );
	count = vfsGetFileCount( filename );

	/* load them all */
	for ( i = 0; i < count; i++ )
	{
		/* load shader list */
		sprintf( filename, "%s/shaderlist.txt", game->shaderPath );
		LoadScriptFile( filename, i );
```

Currently radiant loads the `shaderlist.txt` from VFS instead of loading it (them) from the underlying package.

As a side note, NetRadiant loads them all too: each pk3 can ship its own shaderlist.txt, which is very convenient.
