### ISSUE TITLE
XML parser failed on win xp

### ISSUE THREAD

**Issue by Garux** [TTimo/GtkRadiant#595]
@TTimo i'v tried recent build @ xp box
this:

> Copy D:/Program Files/GtkRadiant-20180122/installs/Q3Pack/install//missionpack/textures/base_wall2/techfloor_kc_blue.tga -> N:\q2\4/missionpack/textures/base_wall2/techfloor_kc_blue.tga
Writing game file: D:/Program Files/GtkRadiant-20180122/games/q3.game
Scanning for game description files: D:/Program Files/GtkRadiant-20180122/games
D:/Program Files/GtkRadiant-20180122/games/q3.game
XML parser failed on 'D:/Program Files/GtkRadiant-20180122/games/q3.game'
mGameCombo == NULL
No games setup, aborting

>GetLastError: ?????? ?????? ?? ????????.

>An unrecoverable error has occured.
Would you like to edit Preferences before exiting Radiant?

GtkRadiant-20180122\games\q3.game:
```xml
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<game
  name="Quake III Arena and mods"
  enginepath_win32="N:\q2\4"
  gametools_win32="D:/Program Files/GtkRadiant-20180122/installs/Q3Pack/game"
  prefix=".q3a"
  basegame="baseq3"
/>
```

**Comment by Pan7** [comment]
It fails here https://github.com/TTimo/GtkRadiant/blob/master/radiant/preferences.cpp#L1244
for you but i can't reproduce it myself.

**Comment by Pan7** [comment]
is libxml2.dll missing?

**Comment by TTimo** [comment]
It’s probably a non-xp-friendly libxml2.dll

**Comment by Garux** [comment]
There is no any libxml, plus no one is linked
I wonder how it works on other systems kinda
![default](https://user-images.githubusercontent.com/1734117/35645776-0408ca8c-06de-11e8-842e-025c3f873451.png)

**Comment by TTimo** [comment]
I suspect we statically link it (libxml2.lib) but it was likely compiled with a non XP friendly toolchain.

**Comment by Pan7** [comment]
Maybe the "Visual C++ Redistributable for Visual Studio 2017" is missing?
x86 https://go.microsoft.com/fwlink/?LinkId=746571
x64 https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by Garux** [comment]
woo-hoo
finally running on xp after 6 years
![default](https://user-images.githubusercontent.com/1734117/35651519-10c8c836-06f1-11e8-81ce-a359db668486.png)
though redist 2017 requirement is unobvious (no dlls missing even); Do newer windows prompt about that?

**Comment by ensiform** [comment]
The link is mentioned as mandatory on irc I know that, but newer versions of Windows might ship with it.
