### ISSUE TITLE
radiant keeps chrashing on windows

### ISSUE THREAD

**Issue by thunderpwn** [TTimo/GtkRadiant#598]
[GTKRadiant-1.6.6-20180219-210644.zip](https://github.com/TTimo/GtkRadiant/files/1738069/GTKRadiant-1.6.6-20180219-210644.zip)

**Comment by thunderpwn** [comment]
this is the latest from your site

**Comment by Pan7** [comment]
Does it crash on startup? Does it create a crash log file (.dmp)? What does the radiant.log file say?

**Comment by thunderpwn** [comment]
dump file is in first message inside the zip
no it runs for a little while

**Comment by thunderpwn** [comment]
[station_gold_beta1.zip](https://github.com/TTimo/GtkRadiant/files/1741352/station_gold_beta1.zip)
it chrashes on this new map I just started

**Comment by thunderpwn** [comment]
and where do I fin radiant.log?

**Comment by 0bsidian** [comment]
Do you have the new Windows Visual C++ Redistributables installed? I believe you need 2017 with the current version.

**Comment by Pan7** [comment]
It is crashing in atioglxx.dll (version 6.14.10.13411).
Can you update your (ATI) video drivers?

**Comment by thunderpwn** [comment]
tried with newest driver, same problem.. I will check that @0bsidian

**Comment by thunderpwn** [comment]
mapping again! thx @obsidian.. You should update the link in downloads. It points to 2015 and that doesnt help!
Thx a lot guys for your effort and work

**Comment by TTimo** [comment]
I suspect whatever fixed the driver crash isn't really the redistributable update.

**Comment by thunderpwn** [comment]
and you're right, it now works on my map.. But when I try to  load a map from another mapper who wanted me to check something it again crash

**Comment by thunderpwn** [comment]
wierd, never had this problem before.. is there something big you have changed now @TTimo ?

**Comment by TTimo** [comment]
Do older releases still work? E.g. not a regression in the ATI drivers?

We removed some ancient 'GL bug workaround' in the last few months. One of them had to be put back in even.

What GPU, OS etc.?

**Comment by ensiform** [comment]
I wonder if MSVC 2015 and 2017 share dll names and there was a possible issue because of that (IE: it tried to load older 2015 version but failed to use it because it was wrong)

**Comment by TTimo** [comment]
No, I'm pretty sure the runtimes for any and all Visual Studio versions can cohabit on the same systems...

**Comment by thunderpwn** [comment]
win7 professional x64, amd A10 cpu, 8gb ram, gpu AMD Radeon 7660G + 7500/7600 Dual graphics
and yes version before this one worked for me

**Comment by thunderpwn** [comment]
found GtkRadiant-1.6.4-20170318 hidden away on my machine, will test it

**Comment by thunderpwn** [comment]
no it doesnt work, it crash immediately.
will try some other driver if I can find one

**Comment by thunderpwn** [comment]
I will do one last try on this and get rid of all VS stuff I got and then install again

**Comment by thunderpwn** [comment]
ok after al VS stuff removed and installed VSRedist 2015 it seems to work pretty stable, not 100% but its so its possible to map.
