### ISSUE TITLE
Setting average sampled color from texture to light entity uses commas for color

### ISSUE THREAD

**Issue by Aciz** [TTimo/GtkRadiant#603]
Pressing `SHIFT + MOUSE3` to set average sampled color of currently selected texture to light color uses commas as separators for `_color` values. I believe the issue is this line:
https://github.com/TTimo/GtkRadiant/blob/8557f1820f8e0c7cef9d52a78b2847fa401a4a95/radiant/drag.cpp#L498

which should instead be:

```cpp
strBuff.Format( "%.6f %.6f %.6f",pTex->color[0], pTex->color[1], pTex->color[2] );
```

I am certainly not 100% sure if this is the correct solution, but regardless the functionality sets wrong separator.

**Comment by Pan7** [comment]
It creates space separated values for me like this:
> 0.131906 0.131906 0.566156

**Comment by Aciz** [comment]
@Pan7 This is the result I'm getting.

https://i.imgur.com/a1oVdRh.png

From what I've been googling, I believe locale affects the separator? I'm on Windows 10 Pro x64, with Finnish locale & keyboard layout.

**Comment by Pan7** [comment]
The problem is CString Format is using your locale.
See https://github.com/TTimo/GtkRadiant/blob/8557f1820f8e0c7cef9d52a78b2847fa401a4a95/radiant/main.cpp#L462

**Comment by Aciz** [comment]
Yes, that's what I understood as well, after looking more into it. But is there no way to force it to use dots as separators? Because commas do not work, the lights just default to white.

**Comment by Pan7** [comment]
It should not use commas but i don't find where it sets the locale wrong.

**Comment by Aciz** [comment]
I have fixed this by changing the formatting options of my locale to use dots instead of commas as decimal symbol. Hopefully it won't mess up other things anywhere. Still, isn't there a way to force it to use dots instead of whatever is the locale default?

![](https://i.imgur.com/O7OTUAD.png)

**Comment by Garux** [comment]
![commas](https://user-images.githubusercontent.com/1734117/36704042-63c0a6ac-1b56-11e8-850d-44d6ca37b202.png)
moar commas

**Comment by Aciz** [comment]
These used to be commas for me as well, just never paid attention to them since commas work fine there. Now these are dots as well though.

**Comment by Garux** [comment]
FP for mouse sensitivity doesn't work tho ¯\_(ツ)_/¯
