### ISSUE TITLE
Gamepack typo for grenade launcher shader

### ISSUE THREAD

**Issue by Pan7** [TTimo/GtkRadiant#607]
There is a typo for the models/weapons2/grenadel/grenadel shader in installs\Q3Pack\install\baseq3\scripts\models.shader 
it should be:
map models/weapons2/grenadel/grenadel.jpg

**Comment by 0bsidian** [comment]
Fixed. Thanks.

**Comment by TTimo** [comment]
So did we break something, or did we change something that doesn't really matter, or can we close this?

**Comment by Pan7** [comment]
The radiant shaders aren't installed into the baseq3/scripts folder of quake anymore. 
So it doesn't matter. If you add a weapon model as a map model it will have a default radiant shader for compiling.
Don't know how the original shader looks like. is it hardcoded, just a default shader?

**Comment by Garux** [comment]
Since when shaders aren't installed into the baseq3/scripts folder? They were in 20180122.
Original shader is default one + hardcoded lightingDiffuse i bet.
Basically Q3 gamepack shaders are trashed (and always were) with deprecated/maps missing ones.
