### ISSUE TITLE
Cubic clipping distance preferences and key shortcut issues

### ISSUE THREAD

**Issue by jdolan** [TTimo/GtkRadiant#609]
Performance on my 2016 MBP (quad i7, Radeon 560) is _abysmal_ with the far-z clipping feature no longer available (at least no longer available in the UI). When looking at corners of the map, the 3D view is responsive, and looking around feels nice. But as soon as I look towards the center of the map, the 3D view plummets to 10fps, and it's a real chore to look around. Was this feature intentionally removed? Is it still available via editing a config file?

**Comment by Aciz** [comment]
View -> Cubic clipping. It was recently defaulted off.

**Comment by jdolan** [comment]
Thanks. Certainly helps! Is there a way to set the distance? A slider for this might be nice. I thought this feature used to live in the preferences menu, too?

**Comment by Aciz** [comment]
`CTRL + [` and `CTRL + ]` are supposedly the keyboard shortcuts to adjust cubic clipping distance, but I'm not sure if they work. If they do, might only be a thing on US keyboards. There's no way to adjust it on my keyboard at least which used Nordic layout.

**Comment by Mateos81** [comment]
For reference: https://github.com/TTimo/GtkRadiant/pull/597

Expected it ^^'

As for shortcuts: I can say on AZERTY layout they don't work. A slider is a neat idea :)

**Comment by TTimo** [comment]
So hu .. revert #597 or leave things as they are? Maybe have a higher default?

Folks with crappy hardware or broken drivers will have problems anyway. This is not where we can address that.

**Comment by jdolan** [comment]
I don't a strong preference. Interestingly, it was my external GPU (8GB RX 580) that runs Radiant horribly. My onboard, discrete GPU (2GB RX 560 Pro) does just fine. Go figure.

I think a preference for tuning the clipping distance is something only a very small percentage of users might ever find useful.
