### ISSUE TITLE
Floodlight overbrights styled lightmaps

### ISSUE THREAD

**Issue by Aciz** [TTimo/GtkRadiant#616]
So this issue is a precaution for #605. If the floodlight implementation was ported without functionality alterations from NetRadiant, styled lightmaps are messed up when using floodlight, as seen here:

https://streamable.com/l6lm8

While the expected result should look something like this:

https://streamable.com/6mm3u

@isRyven has made a fix for this in his own version of q3map2 as per my request when I wanted to use floodlight and styled lightmaps in one of my recent maps that I made, by both adjusting floodlight calculations and adding `-nofloodstyles` switch to disable floodlighting completely on styled lightmaps. You can see the fix here:

https://github.com/id-tech-3-tools/map-compiler/pull/12

He can probably chime in more on the technical aspect of this as well.

**Comment by TTimo** [comment]
@illwieckz what should we do here?

**Comment by illwieckz** [comment]
oh, yet another q3map2 fork I can add to my [comparison tool](http://github.com/illwieckz/compare_radiant)! :grin:

if the merge is straightforward it can be good to merge it back on both gtkradiant/netradiant trees, I'll have a look on this.

**Comment by illwieckz** [comment]
@Aciz do this change would be enough:
https://github.com/Garux/netradiant-custom/commit/1a614efce1f5384489324a6468fac8908492f5ba

Or those extra command line switches are required?

---
Note: new url to original fix is https://github.com/id-tech-3-tools/map-compiler/pull/12

**Comment by Aciz** [comment]
Yes, the one made by Garux is enough to solve the main issue.

**Comment by illwieckz** [comment]
@Aciz you said “_main issue_”, is there secondary issues?

**Comment by Aciz** [comment]
@illwieckz I guess there really isn't a secondary issue(s), my wording was perhaps poor :P The point was that floodlighting algorithm didn't really work well with styled lightmaps, so it was adjusted. The switch to disable floodlighting on them is another way to fix the issue, which makes sense in realism aspect.
