### ISSUE TITLE
Linux download links are broken

### ISSUE THREAD

**Issue by wmcmurray** [TTimo/GtkRadiant#621]
Hello guys !

This issue is not related to the code itself but with the download page on the website : 
http://icculus.org/gtkradiant/downloads.html
( I couldn't find a better way to contact you, sorry ! )

The download links of "GtkRadiant 1.6.4 for Linux 64-bit" (and 32 bit) seems to be broken.

It looked like a redirection from amazon because they changed their domain/subdomain name structure, so I tried to guess what it could be now and I figured out that instead of this broken link : 

http://www.amazonaws.com/GtkRadiant/GtkRadiant-1.6.4-Linux-x86_64-20131213.tar.gz

The link should be : 

http://s3.amazonaws.com/GtkRadiant/GtkRadiant-1.6.4-Linux-x86_64-20131213.tar.gz

Hope it helps ! :)

**Comment by TTimo** [comment]
Fixed, thank you. Let's hope no one uses those binaries however. They are very outdated, folks on Linux should compile themselves for now.
