### ISSUE TITLE
Crash on start (1.6.6 & 1.6.5)

### ISSUE THREAD

**Issue by SimonSDA** [TTimo/GtkRadiant#622]
Radiant user from ancient times here (Q2, W:ET & ET:QW). Cannot get Radiant to start (1.6.6 or 1.6.5) for editing Quetoo (also tried for Quake2) on Win10 x64. It will load to the UI and then crash... Here is the log:

Started logging to Z:/SymoGames/Radiant 1.6.5/radiant.log
Today is: Wed Apr 18 16:27:00 2018
This is radiant '1.6.5' compiled Feb 25 2017
http://icculus.org/GtkRadiant/
XML property file 'Z:/SymoGames/Radiant 1.6.5/quetoo.game/local.pref' invalid/not found, creating blank properties tree
OpenGL not ready - postpone texture compression capability check
OpenGL not ready - postpone ATI bug workaround setup
Disabling Windows composition
Saving local.pref with default pref values
Wrote XML property file 'Z:/SymoGames/Radiant 1.6.5/global.pref'
Wrote XML property file 'Z:/SymoGames/Radiant 1.6.5/quetoo.game/local.pref'
RC file Z:\SymoGames\Radiant 1.6.5\radiantgtkrc not found
Loading GL library: opengl32.dll ...Done.
GDK's coordinate system is offset by 0 over the x-axis and 0 over the y-axis from Windows' coordinate system.
'Z:/SymoGames/Radiant 1.6.5/global.xlink' not found / parse failed
Processing .xlink file 'Z:/SymoGames/Radiant 1.6.5/installs/QuetooPack/game/game.xlink'
'C:/GtkRadiant/GtkRadiant/install/installs/QLPack/game/game.xlink' not found / parse failed
loading synapse XML config file 'Z:/SymoGames/Radiant 1.6.5/installs/QuetooPack/game/synapse.config'
Synapse Scanning modules path: Z:/SymoGames/Radiant 1.6.5/modules/
Found 'Z:/SymoGames/Radiant 1.6.5/modules/bkgrnd2d.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/bkgrnd2d.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/bobtoolz.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/bobtoolz.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/camera.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/camera.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/entity.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/entity.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/fgd.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/fgd.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/gtkgensurf.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/gtkgensurf.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/hydratoolz.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/hydratoolz.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/image.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/image.dll'
Dynamic APIs for client 'image formats JPG TGA PCX BMP module built Feb 25 2017 1.6.5'
1 dynamic interfaces parsed for 'image'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/imagehl.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/imagehl.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/imagem8.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/imagem8.dll'
Dynamic APIs for client 'M8 M32 formats module built Feb 25 2017 1.6.5'
api: 'VFS' minor: 'pk3'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/imagepng.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/imagepng.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/imagewal.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/imagewal.dll'
Dynamic APIs for client 'WAL formats module built Feb 25 2017 1.6.5'
1 dynamic interfaces parsed for 'image'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/map.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/map.dll'
Dynamic APIs for client 'MAP format module built Feb 25 2017 1.6.5'
1 dynamic interfaces parsed for 'map'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/mapxml.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/mapxml.dll'
Dynamic APIs for client 'XMAP module built Feb 25 2017 1.6.5'
1 dynamic interfaces parsed for 'xmap'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/model.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/model.dll'
Dynamic APIs for client 'picomodel loader module built Feb 25 2017 1.6.5'
2 dynamic interfaces parsed for 'model'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/prtview.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/prtview.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/shaders.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/shaders.dll'
Dynamic APIs for client 'Q3/Half-Life shaders module built Feb 25 2017 1.6.5'
2 dynamic interfaces parsed for 'shaders'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/spritemodel.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/spritemodel.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/surface.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/surface.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/surface_idtech2.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/surface_idtech2.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/textool.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/textool.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/vfspak.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/vfspak.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/vfspk3.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/vfspk3.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/vfsqlpk3.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/vfsqlpk3.dll'
Found 'Z:/SymoGames/Radiant 1.6.5/modules/vfswad.dll'
Enumerate interfaces on 'Z:/SymoGames/Radiant 1.6.5/modules/vfswad.dll'
Synapse Scanning modules path: Z:/SymoGames/Radiant 1.6.5/plugins/
Synapse Scanning modules path: Z:/SymoGames/Radiant 1.6.5/installs/QuetooPack/game/modules/
Synapse Scanning modules path: Z:/SymoGames/Radiant 1.6.5/installs/QuetooPack/game/plugins/
Dynamic APIs for client 'Radiant - synapse core built Feb 25 2017 1.6.5'
5 dynamic interfaces parsed for 'core'
CSynapserServer::Resolve adding new client slot 'Radiant - synapse core built Feb 25 2017 1.6.5'
'PK3 VFS module built Feb 25 2017 1.6.5' activated
'Q3/Half-Life shaders module built Feb 25 2017 1.6.5' activated
'picomodel loader module built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "shaders"
  found in Q3/Half-Life shaders module built Feb 25 2017 1.6.5
'Sprite Model module built Feb 25 2017 1.6.5' activated
'Entity module built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
'2d Background plugin built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "shaders"
  found in Q3/Half-Life shaders module built Feb 25 2017 1.6.5
'bobToolz module built Feb 25 2017 1.6.5' activated
'Camera plugin v1.0 - Arnout van Meer - built Feb 25 2017 1.6.5' activated
'GtkGenSurf - built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
'HydraToolz plugin built Feb 25 2017 1.6.5' activated
'PrtView module built Feb 25 2017 1.6.5' activated
'Texture Tools plugin built Feb 25 2017 1.6.5' activated
'image formats JPG TGA PCX BMP module built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
'PNG loader module built Feb 25 2017 1.6.5' activated
'XMAP module built Feb 25 2017 1.6.5' activated
'Surface Dialog (idTech2) module built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
'Builtin .def module built Feb 25 2017 1.6.5' activated
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
checking if we have a single active client for major "VFS"
  found in PK3 VFS module built Feb 25 2017 1.6.5
'MAP format module built Feb 25 2017 1.6.5' activated
Unloading an unused module: 'WAD VFS module built Feb 25 2017 1.6.5'
FreeLibrary 'WAD VFS module built Feb 25 2017 1.6.5'
Unloading an unused module: 'Quake Live PK3 VFS module built Feb 25 2017 1.6.5'
FreeLibrary 'Quake Live PK3 VFS module built Feb 25 2017 1.6.5'
Unloading an unused module: 'PAK VFS module built Feb 25 2017 1.6.5'
FreeLibrary 'PAK VFS module built Feb 25 2017 1.6.5'
Unloading an unused module: 'Surface Dialog (Quake 3) module built Feb 25 2017 1.6.5'
FreeLibrary 'Surface Dialog (Quake 3) module built Feb 25 2017 1.6.5'
Unloading an unused module: 'WAL formats module built Feb 25 2017 1.6.5'
FreeLibrary 'WAL formats module built Feb 25 2017 1.6.5'
Unloading an unused module: 'M8 M32 formats module built Feb 25 2017 1.6.5'
FreeLibrary 'M8 M32 formats module built Feb 25 2017 1.6.5'
Unloading an unused module: 'imagehl formats module built Feb 25 2017 1.6.5'
FreeLibrary 'imagehl formats module built Feb 25 2017 1.6.5'
Unloading an unused module: '.fgd eclass module built Feb 25 2017 1.6.5'
FreeLibrary '.fgd eclass module built Feb 25 2017 1.6.5'
last project has version -1, this binary wants version 2 - regenerating from the template
Scanning template version in Z:/Games/Quetoo/share/default/scripts/default_project.proj
Version key not found in Z:/Games/Quetoo/share/default/scripts/default_project.proj
Loading project file: "Z:/Games/Quetoo/share/default/scripts/default_project.proj"
basepath    : Z:/Games/Quetoo/share/default/
entitypath  : Z:/Games/Quetoo/share/default/scripts/entities.def
Loaded a template project file
Save project file 'Z:\Dox\My Games\Quetoo\default\scripts\user2.proj'
Setting current project in prefs to "Z:\Dox\My Games\Quetoo\default\scripts\user2.proj"
Wrote XML property file 'Z:/SymoGames/Radiant 1.6.5/global.pref'
Wrote XML property file 'Z:/SymoGames/Radiant 1.6.5/quetoo.game/local.pref'
vfs directory: Z:\Dox\My Games\Quetoo\default
vfs directory: Z:/Games/Quetoo/share/default
  pak file: Z:/Games/Quetoo/share/default/player-qforcer.pk3
  pak file: Z:/Games/Quetoo/share/default/player-guard.pk3
  pak file: Z:/Games/Quetoo/share/default/player-gork.pk3
  pak file: Z:/Games/Quetoo/share/default/player-dragoon.pk3
  pak file: Z:/Games/Quetoo/share/default/player-bunker.pk3
  pak file: Z:/Games/Quetoo/share/default/map-warehouse.pk3
  pak file: Z:/Games/Quetoo/share/default/map-wake.pk3
  pak file: Z:/Games/Quetoo/share/default/map-trial.pk3
  pak file: Z:/Games/Quetoo/share/default/map-torn.pk3
  pak file: Z:/Games/Quetoo/share/default/map-tokays.pk3
  pak file: Z:/Games/Quetoo/share/default/map-slimyplace.pk3
  pak file: Z:/Games/Quetoo/share/default/map-sandbox.pk3
  pak file: Z:/Games/Quetoo/share/default/map-rage.pk3
  pak file: Z:/Games/Quetoo/share/default/map-pits.pk3
  pak file: Z:/Games/Quetoo/share/default/map-lilith.pk3
  pak file: Z:/Games/Quetoo/share/default/map-lavatomb.pk3
  pak file: Z:/Games/Quetoo/share/default/map-hallways.pk3
  pak file: Z:/Games/Quetoo/share/default/map-gym.pk3
  pak file: Z:/Games/Quetoo/share/default/map-grunt.pk3
  pak file: Z:/Games/Quetoo/share/default/map-gehenna.pk3
  pak file: Z:/Games/Quetoo/share/default/map-fragpipe.pk3
  pak file: Z:/Games/Quetoo/share/default/map-fractures.pk3
  pak file: Z:/Games/Quetoo/share/default/map-edge.pk3
  pak file: Z:/Games/Quetoo/share/default/map-darkzone.pk3
  pak file: Z:/Games/Quetoo/share/default/map-chastity.pk3
  pak file: Z:/Games/Quetoo/share/default/map-aerowalk.pk3
ScanFile: Z:/Games/Quetoo/share/default/scripts/entities.def
Searching VFS for files in sprites/*.* that match entity names...
0 entities were scanned
0 entities that already had models/sprites were ignored
0 non-fixed-size entities were ignored
0 entities did not have matching sprite files
0 entities had sprite files and have been attached
Parsing shader files from Z:/Games/Quetoo/share/default/scripts/shaderlist.txt
Parsing shaderfile scripts/common.shader
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 950/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 388.13
GL_EXTENSIONS: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_Checking for extension 'GL_ARB_texture_compression'...Found
Checking for extension 'GL_EXT_texture_compression_s3tc'...Found
OpenGL texture compression enabled
ATI bug workaround disabled

Event Viewer log:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-04-18T15:33:01.022293500Z" /> 
  <EventRecordID>17019</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-0L9P8S0</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>radiant.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>58b211ed</Data> 
  <Data>nvoglv32.DLL</Data> 
  <Data>23.21.13.8813</Data> 
  <Data>59f352e9</Data> 
  <Data>c0000409</Data> 
  <Data>00e0e899</Data> 
  <Data>27c</Data> 
  <Data>01d3d72a7873f047</Data> 
  <Data>Z:\SymoGames\Radiant 1.6.5\radiant.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\nvoglv32.DLL</Data> 
  <Data>5a6d0387-9c2c-44f4-805d-b9a909b29f69</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

and this -

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="NVIDIA OpenGL Driver" /> 
  <EventID Qualifiers="49152">1</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-04-18T15:33:00.938294700Z" /> 
  <EventRecordID>17018</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-0L9P8S0</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Unable to recover from a kernel exception. The application must close. Error code: 3 (subcode 7) (pid=636 tid=2028 radiant.exe 32bit) Visit http://www.nvidia.com/page/support.html for more information.</Data> 
  </EventData>
  </Event>

**Comment by SimonSDA** [comment]
Also this -

Log Name:      Application
Source:        Windows Error Reporting
Date:          18/04/2018 16:36:38
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-0L9P8S0
Description:
Fault bucket 2046498080101446487, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: radiant.exe
P2: 0.0.0.0
P3: 58b211ed
P4: nvoglv32.DLL
P5: 23.21.13.8813
P6: 59f352e9
P7: 00e0e899
P8: c0000409
P9: 00000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE4AA.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5D5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5D3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5F3.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_radiant.exe_17a0239987eaa64bfadb5f3ea449493df3be7c5_2037f594_107deb90

Analysis symbol: 
Rechecking for solution: 0
Report ID: 18671def-6615-42ad-af77-ca2ab7a59495
Report Status: 268435456
Hashed bucket: 4b809c1fe92fb9f4cc669f2939f73357
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-18T15:36:38.365322800Z" />
    <EventRecordID>17024</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-0L9P8S0</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2046498080101446487</Data>
    <Data>5</Data>
    <Data>BEX</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>radiant.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>58b211ed</Data>
    <Data>nvoglv32.DLL</Data>
    <Data>23.21.13.8813</Data>
    <Data>59f352e9</Data>
    <Data>00e0e899</Data>
    <Data>c0000409</Data>
    <Data>00000007</Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE4AA.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5D5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5D3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE5F3.tmp.txt</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_radiant.exe_17a0239987eaa64bfadb5f3ea449493df3be7c5_2037f594_107deb90</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>18671def-6615-42ad-af77-ca2ab7a59495</Data>
    <Data>268435456</Data>
    <Data>4b809c1fe92fb9f4cc669f2939f73357</Data>
  </EventData>
</Event>

**Comment by SimonSDA** [comment]
Thanks - I've tried with 1.6.6 and it crashes with the same thing :(. I also tried with Quake2. Here are the exception details from a VS debug (for 1.6.5 and 1.6.6 its the same):

Unhandled exception at 0x51100D87 (nvoglv32.dll) in radiant.exe

**Comment by SimonSDA** [comment]
I found the culprit by looking here - https://github.com/TTimo/GtkRadiant/issues/569

Turning off Instant Replay in GeForce Experience seems to have sorted it :o

**Comment by TTimo** [comment]
duplicate
