### ISSUE TITLE
light bleeding

### ISSUE THREAD

**Issue by thunderpwn** [TTimo/GtkRadiant#640]
I know this isnt a new issue, but it is really annoying for us mappers.
Have you tried todo anything about it?
![2019-05-18-100837-siwa2_beta1](https://user-images.githubusercontent.com/3218273/57966698-d2f58e80-7955-11e9-95bc-d28a5d1a7276.jpg)
I've tried with caulk, and those wooden logs under but nothing seems to help

**Comment by Garux** [comment]
@thunderpwn i'm trying to do something with this now, can you provide example map with this?  
It looks different to cases i have, as ceiling is thick enough to make no problem.

**Comment by Mateos81** [comment]
I think you can use the Siwa Oasis source and check the building next to the Old City flag, where you can find health & ammo cabinets; I recall a light bleed there

**Comment by Garux** [comment]
These onee?
![image](https://user-images.githubusercontent.com/1734117/66037698-e413f600-e518-11e9-9310-0e39c34caaba.png)
Aren't they there due to light sources, lighting directly?
