### ISSUE TITLE
Guix package: mkdir .../games/ failed: errno: Read-only file system

### ISSUE THREAD

**Issue by Ambrevar** [TTimo/GtkRadiant#641]
I'm trying to package GtkRadiant for [Guix](https://guix.gnu.org).

Compilation runs almost fine (bar issue #631).
When I launch the program, I can choose Quake III Arena and mods, and select the `~/.q3a` game directory.  When I click OK, I get this message:

``` sh
mkdir /gnu/store/30i942vmmv9a0sil5abcj2anxi04i5cc-gtk-radiant-1.5-1.3f79dc3/bin/games/ failed - check your permissions
errno: Read-only file system
An unrecoverable error has occured.
Would you like to edit Preferences before exiting Radiant?
```
This makes sense since the gtk-radiant installation folder is read-only.
Is there a way to specify that this "games" folder should be created in the users' home?

**Comment by TTimo** [comment]
No, there isn't. The install/ folder needs to be writable, the editor binary completes some installation and configuration steps once it gets pointed at a game to configure for.

**Comment by Ambrevar** [comment]
So this means the editor cannot be installed on a multi-user system as root?

**Comment by TTimo** [comment]
Correct - that's not possible. An heritage from being a Windows piece of software originally, and being written 25 years ago.

It's a reasonably small set of files for nowadays systems so you could just sync the whole thing to ~/.local/share before the first execution though.

**Comment by Ambrevar** [comment]
Thanks for confirming.  I'll go with a wrapper then.
