### ISSUE TITLE
HELP!!! Gtkradiant 1.6.6

### ISSUE THREAD

**Issue by PandaRemix** [TTimo/GtkRadiant#646]
Hello! I have a problem. I'm using gtkradiant 1.6.6 and editing in quakelive I can't get the mapobjects to see. I use even those in quake3 and it doesn't show them. When I edit in Quake3 the mapobjects are shown perfectly, I don't know why in quakelive it doesn't show them.

https://i.ibb.co/xsXsRz8/HELP.png

https://i.ibb.co/SQLnx7B/IFS.png

**Comment by TTimo** [comment]
No sure what's going on, but I would try first to configure things so there are no spaces in your various installation paths. (`C:\Quake 3 Arena def` -> `C:\q3def` or similar).

Or .. it even looks like the models have been expanded outside the baseq3 tree? I don't think that works, they are supposed to be expanded into your baseq3/?

**Comment by Pan7** [comment]
He fixed it with "changed the mapobjects folder from quake3 to baseq3 from quakelive."
