### ISSUE TITLE
Dependencies? 

### ISSUE THREAD

**Issue by marcikaa78** [TTimo/GtkRadiant#699]
Hi, I want to build gtkradiant, but I get 200+ errors due to the dependencies missing, where to get them?
![image](https://github.com/user-attachments/assets/9a702d4c-cf62-4e93-8812-b3289c19af1e)

**Comment by TTimo** [comment]
Are you following the build guide for Windows? You can find it on the website.

**Comment by marcikaa78** [comment]
Yes I cloned the repo via --recursive, but git somehow forgot to download the libs

**Comment by TTimo** [comment]
This is the build guide: https://icculus.org/gtkradiant/documentation/windows_compile_guide/

**Comment by marcikaa78** [comment]
Thank you, I didn't see it!
